### ISSUE TITLE
Error: executing "npm run watch" fails after following readme steps

### ISSUE THREAD

**Issue by alex-drocks** [google/eleventy-high-performance-blog#15]
Hey this template seems awesome thats why I wanted to test it for myself.
Thanks for publishing it.

I have a problem where I cannot run the **npm watch script** without getting errors by following the steps in the readme.
More precisely, I can't run any npm scripts that start with the "./node_modules..." string. But I do have the node modules folder installed properly.

Steps to reproduce on my computer:

1. Clone repository on my computer.
2. Open folder in my code editor.
3. run npm install from that folder
4. run npm watch (concurrently "eleventy --serve" "npm run js-build-watch" "npm run test-watch")
5. console outputs many errors where the first error says that the "." command is unknown (all npm scripts that start with a dot fail)

Hope this helps thank you again.
Alex

EDIT: do I need some kind of global dependencies on my computer ? I have not seen it mentionned in the readme and I never used eleventy before.

**Comment by bost-ty** [comment]
I'm having this issue as well. Looks like src/main.js isn't being turned into min.js and stored in the correct location.

Creating a min.js file in _site/js/, even blank, fully renders and serves with no errors. I believe the problem lies in the config for either rollup (see rollup.config.js) or the eleventy config not finding the files. Should main.js be moved up from src/ to the root or to the root's js/ folder so that it's correctly exported like the file that's currently there, cached.js?

**Comment by cramforce** [comment]
This was likely fixed by https://github.com/google/eleventy-high-performance-blog/commit/534e6572398dd1ad82a753c518489ebe74aceb43 but please reopen if the issue persists.

**Comment by alex-drocks** [comment]
> This was likely fixed by [534e657](https://github.com/google/eleventy-high-performance-blog/commit/534e6572398dd1ad82a753c518489ebe74aceb43) but please reopen if the issue persists.

Thanks a lot it works perfectly now.

**Comment by hhh968574** [comment]
هذه
