### ISSUE TITLE
can't access property getBoundingClientRect error

### ISSUE THREAD

**Issue by Ben1980** [google/eleventy-high-performance-blog#76]
I'm getting the following error with Firefox (dev edition), regardless it seems to not affect the page itself.
https://thoughts-on-coding.com/2021/03/11/from-wordpress-to-11ty/
```
Uncaught TypeError: can't access property "getBoundingClientRect", document.querySelector(...) is null
    <anonymous> main.js:232
    ResizeObserverCallback* main.js:229
    <anonymous> main.js:270
main.js:232:15
    <anonym> main.js:232
    (Async: ResizeObserverCallback)
    <anonym> main.js:229
    <anonym> main.js:270
```

**Comment by cramforce** [comment]
I'm really puzzled by this one. It must be a customization that you made on your side, as it doesn't happen with the unchanged demo.

I'm struggling to explain how this could happen since the selector does eventually work and the script element has defer and hence should only run after the DOM was parsed.

**Comment by Ben1980** [comment]
Yes you're right, it's caused by MailChimp's mc-validate.js
