### ISSUE TITLE
Build fails when image processing utility encounters .svg files in markdown

### ISSUE THREAD

**Issue by indcoder** [google/eleventy-high-performance-blog#9]
More details here:
https://github.com/HackerspaceMumbai/goog11ty/issues/6

**Comment by MyIsaak** [comment]
The error comes from https://github.com/oliver-moran/jimp/blob/b038cba64ee72224efe0fe0f9e8f8c8fce0e3711/packages/core/src/utils/image-bitmap.js#L167 when trying to create blurred image using `jimp` (however svg format isn't supported).

IMO one should write a custom `jimp` plugin rasterizes SVG using `sharp` since its already there in the project. Below is an example using sharp to rasterize SVG into PNG:
https://github.com/lovell/sharp/blob/79f476ae4d10bbaf956d915e015be8873a9e8f17/test/unit/svg.js#L9-L27

**Comment by indcoder** [comment]
Yeah its a design decision for Malte et al. Its basically converting .svg to .png , which can be done manually by the blog author himself (thats what I did 😀) Bur perhaps if component encounters a SVG it need not do the processing since Vector based images are pretty optimized(my assumption). 

I listed this in the repo issue so that other blog users of this template are aware of it. Image optimization for the web is a complex beast so wanted to ensure the template users are informed of the best practice.
